import 'package:shared_preferences/shared_preferences.dart';

import '../utils/logger.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

/// Persists YouTube cookies and user-agent obtained via browser login
/// so that yt-dlp can use them for authenticated requests.
class YouTubeCookieService {
  static const _kCookiesKey = 'youtube_cookies';
  static const _kUserAgentKey = 'youtube_user_agent';

  final SharedPreferences _prefs;
  YouTubeCookieService(this._prefs);

  /// Returns raw cookie header string (e.g. "SID=...; SSID=...; HSID=...")
  String? get cookieHeader => _prefs.getString(_kCookiesKey);

  /// Returns the user-agent string that was used during login.
  String? get userAgent => _prefs.getString(_kUserAgentKey);

  bool get hasCookies {
    final c = cookieHeader;
    return c != null && c.isNotEmpty;
  }

  /// Save cookies from a list of {name, value} maps.
  /// Also saves the user-agent if provided.
  Future<void> saveCookies(List<dynamic> cookies, {String? userAgent}) async {
    // Формируем чистый List<Map<String, String>>
    final List<Map<String, String>> formattedCookies = [];

    for (final c in cookies) {
      final name = c['name'] as String? ?? '';
      if (name.isEmpty) continue;

      final value = c['value'] as String? ?? '';
      final domain = c['domain'] as String? ?? '.youtube.com';
      final includeSubdomains = c['includeSubdomains'] as String? ?? 'TRUE';
      final path = c['path'] as String? ?? '/';
      final secure = c['secure'] as String? ?? 'TRUE';
      final expiration = c['expiration'] as String? ?? '0';

      formattedCookies.add({
        'domain': domain,
        'includeSubdomains': includeSubdomains,
        'path': path,
        'secure': secure,
        'expiration': expiration,
        'name': name,
        'value': value,
      });
    }

    // Безопасно кодируем весь список в JSON
    final jsonString = jsonEncode(formattedCookies);

    AppLogger.log('Saving YouTube cookies', tag: 'YouTubeCookieService');
    await _prefs.setString(_kCookiesKey, jsonString);

    if (userAgent != null && userAgent.isNotEmpty) {
      await _prefs.setString(_kUserAgentKey, userAgent);
    }
  }

  /// Build the cookie header map for HTTP requests.
  Map<String, String> get cookieHeaders {
    final c = cookieHeader;
    if (c == null || c.isEmpty) return {};
    return {'cookie': c};
  }

  /// Clear stored cookies and user-agent (logout).
  Future<void> clearCookies() async {
    await _prefs.remove(_kCookiesKey);
    await _prefs.remove(_kUserAgentKey);
  }
}

Future<File> createTempCookieFile(String header) async {
  final tempDir = await getTemporaryDirectory();
  final file = File(p.join(tempDir.path, 'cookies_${DateTime.now().millisecondsSinceEpoch}.txt'));

  final buffer = StringBuffer();
  buffer.writeln('# Netscape HTTP Cookie File');
  buffer.writeln('# This file is generated by Browser. Do not edit.\n');

  // Достаем JSON из Prefs
  final jsonString = header;
  if (jsonString.isNotEmpty) {
    final List<dynamic> decoded = jsonDecode(jsonString);

    for (final item in decoded) {
      final c = Map<String, String>.from(item);

      buffer.writeln(
          "${c['domain']}\t"
              "${c['includeSubdomains']}\t"
              "${c['path']}\t"
              "${c['secure']}\t"
              "${c['expiration']}\t"
              "${c['name']}\t"
              "${c['value']}"
      );
    }
  }

  await file.writeAsString(buffer.toString());
  return file;
}
