
  name: Multi-Platform Build

  on:
    push:
      branches: [ master ]
    workflow_dispatch:

  jobs:
    # --- Сборка для Android (APK) ---
    build-android:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '17'

        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'

        - run: flutter pub get
        - run: flutter build apk --release

        - name: Upload APK
          uses: actions/upload-artifact@v4
          with:
            name: ai-mind-android-apk
            path: build/app/outputs/flutter-apk/app-release.apk


    # --- Сборка для Linux ---
    build-linux:
      runs-on: ubuntu-22.04

      steps:
        - uses: actions/checkout@v4

        - name: Install Linux dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y \
              ninja-build \
              cmake \
              pkg-config \
              libgtk-3-dev \
              liblzma-dev \
              libstdc++-12-dev \
              libsecret-1-dev \
              libwpe-1.0-dev \
              libwpebackend-fdo-1.0-dev \
              libwpewebkit-1.0-dev

        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'

        - run: flutter pub get

        - run: flutter build linux --release

        - name: Upload Linux Build
          uses: actions/upload-artifact@v4
          with:
            name: ai-mind-linux
            path: build/linux/x64/release/bundle/


    # --- Сборка для Windows (EXE) ---
    build-windows:
      runs-on: windows-latest

      steps:
        - uses: actions/checkout@v4

        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'

        - run: flutter pub get
        - run: flutter build windows --release

        - name: Upload Windows Build
          uses: actions/upload-artifact@v4
          with:
            name: ai-mind-windows
            path: build/windows/x64/runner/Release/